### ISSUE TITLE
save_parameters seems missing in current version

### ISSUE THREAD

**Issue by roshan-gopalakrishnan** [NeuromorphicProcessorProject/snntoolbox_applications#1]
from snntoolbox.datasets.utils import save_parameters
ImportError: cannot import name save_parameters

Do you have any updated function for saving parameters ?

**Comment by rbodo** [comment]
I had a look at the git history - it seems this function was moved in June 2017, to [here](https://github.com/NeuromorphicProcessorProject/snn_toolbox/blob/0b0b8a2bf6eac9c4d6b70bf0f54451627c2026af/snntoolbox/parsing/model_libs/lasagne_input_lib.py#L249).
